CC = gcc
CFLAGS = -Wall -Wextra -Werror -pthread

EXEC = autocomplete

SRCS = main.c scanner.c trie.c

OBJS = $(SRCS:.c=.o)

all: $(EXEC)

$(EXEC): $(OBJS)
	$(CC) $(CFLAGS) -o $(EXEC) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(EXEC)
